# server:
#   port:"8080"
#   mode:"debug"

# mysql:
#   username:"root"
#   password:"root"
#   host:"127.0.0.1"
#   port:3306
#   dbname:"student_db"
#   charset:"utf8mb4"
  
# auth:
#   token:"666666"
#   token_header:"Authorization"

  # 服务运行配置
server:
  port: ":8080"
  mode: "debug"

# 数据库连接配置
mysql:
  username: "root"
  password: "root"
  host: "127.0.0.1"
  port: 3306
  dbname: "student_db"
  charset: "utf8mb4"

# 认证配置
auth:
  token: "666666"
  token_header: "Authorization"

#日志配置
logger:
  filename: "./log/app"
  level: "info"
  console: true
  max_size: 10
  max_backups: 5
  max_age: 30
  compress: false

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

# Kafka 配置
kafka:
  brokers:
    - "127.0.0.1:9092"  # 集群地址，多个用逗号分隔
  group_id: "student-service-group" # 消费者组ID
  topic_student_event: "student_event" # 学生变更事件主题
  ack_mode: "wait_for_all" # 应答模式：all=所有副本确认，最可靠
  topic_audit_log: "audit.log"
  topic_import: "student_import"